FROM alpine:latest

WORKDIR /home/devpleno_d30

## add git
RUN apk add --update git

## add git config
RUN git config --global user.name "Mateus José Barbosa"
RUN git config --global user.email "46843918+mateusjbarbosa@users.noreply.github.com"

## add nodejs and packages
RUN apk add --update nodejs npm yarn

# add zsh
RUN apk add --update zsh

# add oh-my-zsh
RUN sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"

EXPOSE 3000